- name: Creates mount point if needed
  become: true
  file:
    path: /mnt/data
    state: directory
    owner: root
    group: root
    mode: '0777'

- name: Get cifs username from vault
  set_fact:
    cifs_un: "{{ lookup('hashi_vault', 'secret=kv/data/cifs-mount-user:user') }}"

- name: Get cifs pw from vault
  set_fact:
    cifs_pw: "{{ lookup('hashi_vault', 'secret=kv/data/cifs-mount-pw:pw') }}"

- name: Write cifs credentials file
  become: true
  ansible.builtin.copy:
    content: "user={{ cifs_un }}\npassword={{ cifs_pw }}"
    dest: "/root/.secure"
    owner: root
    group: root
    mode: '0400'

- name: Mount data
  become: true
  ansible.posix.mount:
    src: //192.168.0.170/Z
    path: /mnt/data
    opts: "credentials=/root/.secure,file_mode=0777,dir_mode=0777,sec=ntlm,vers=1.0,iocharset=utf8"
    state: mounted
    fstype: cifs

- name: Creates mount point if needed
  become: true
  file:
    path: /mnt/steam
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"
    state: directory
    mode: '0755'

- name: Mount steam
  become: true
  ansible.posix.mount:
    src: /dev/sda1
    path: /mnt/steam
    opts: "defaults"
    state: mounted
    fstype: xfs
    passno: "2"
