- name: Create required directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ create_dirs }}"

- name: Installing AUR required packages
  kewlfft.aur.aur:
    name: "{{ item }}"
    update_cache: true
  ignore_errors: true
  loop: "{{ aur_packages }}"

- name: Create ssh directory if it does not exist
  ansible.builtin.file:
    path: "/home/{{ linux_user }}/.ssh"
    state: directory
    mode: '0700'

- name: Write ssh/github key
  ansible.builtin.copy:
    content: "{{ lookup('hashi_vault', 'secret={{ vault_key_path }}') }}"
    dest: "/home/{{ linux_user }}/.ssh/id_rsa"
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"
    mode: '0400'

- name: Add self to docker group
  become: true
  ansible.builtin.user:
    name: "{{ linux_user }}"
    groups: docker
    append: true

- name: Get oh-my-zsh
  ansible.builtin.get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh.sh
    mode: '+x'
  tags: ohmyzsh

- name: Install oh-my-zsh
  ansible.builtin.script:
    cmd: /tmp/ohmyzsh.sh
    creates: ~/.oh-my-zsh
  tags: ohmyzsh

- name: Change shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ linux_user }}"
    shell: /usr/bin/zsh
